version: '3'

services:
  cli:
    image: nestjs/cli
    tty: true
  mysql:
    image: mysql:8.0.5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz@WSX
      MYSQL_DATABASE: account
      MYSQL_USER: root
      MYSQL_PASSWORD: 1qaz@WSX